#!/usr/bin/env sh

INPUT_FILE=$1
HEADER=$(head -n1 "$INPUT_FILE")

PATTERN="^(feat|fix|docs|style|refactor|perf|test|chore)(\(.+\))?: .{1,50}"
# shellcheck disable=SC2034
MERGE_PATTERN="^(Merge ).{0,100}(branch )+.+( into )+"

# shellcheck disable=SC2039
if [[ "$HEADER" =~ $PATTERN || "$HEADER" =~ $MERGE_PATTERN ]]; then
  exit 0
fi

# shellcheck disable=SC2112
function err_print() {
  echo "\033[0;31m$1\033[0m"
}

err_print "commit message '$HEADER' \ndoes not match the pattern: [$PATTERN] or [$MERGE_PATTERN]"

exit 1